apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQy96Q0NBZWNDQVFBd2daQXhD
    ekFKQmdOVkJBWVRBbFpPTVE4d0RRWURWUVFJREFaSVlTQk9iMmt4RHpBTgpCZ05WQkFjTUJraGhJ
    RTV2YVRFUU1BNEdBMVVFQ2d3SGRXNXJibTkzYmpFU01CQUdBMVVFQ3d3SllXNXZibmx0CmIzVnpN
    Uk13RVFZRFZRUUREQXBoYm1oa2FXVndiVzFyTVNRd0lnWUpLb1pJaHZjTkFRa0JGaFZ1TURodWFT
    NWsKYVdWd2NFQm5iV0ZwYkM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dn
    RUtBb0lCQVFDbgphM1ByeXlZNjVqMWh3a2tnQ09Hd3JLRndpYnRUWmNYTUI5WFl5RXFxdTJwajgv
    UVJWMkZNWTlYSS9JUDZXU0VMCnBKUW4wc2FxTHpMUDNXd3Q2TVBnNnQ5RlVKb2QzZHM4RDV6Ykho
    aHBtV0psZDJYTWc5QWJMVEJxSnZLZDErWlgKNDF0eFJtdGNmZVpOMXY2T3U3UCtJOTRyZ1dzR2JR
    ekNFVDVyN25HcnVaUGVrWk45Ym5lQzVKU1F1TFQ3elk2agpWcDQvRU9iZFJRNnV2cEF5eVhkcUFn
    RkdaUFVEbEUrcHJpdlJ5TzM1UXJYQnBxWnVEaFE0L0YrazUvV3l2YzZUClJ4aExuZmlGNFdjUXVX
    UHFMWVFmWVQxVTRuQnRLWURNc0NSVW9NTEJDSGNVeS9hbDU0NnlNYWw3R3RKYTJPYS8KRE4xeEo1
    MitpcFFFd0ROMEw5YzFBZ01CQUFHZ0tUQVNCZ2txaGtpRzl3MEJDUUl4QlF3RFptOXZNQk1HQ1Nx
    RwpTSWIzRFFFSkJ6RUdEQVF4TWpNME1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXp6NWE3TmVo
    b0xhem8wMmZVCkhTM05KM2RncDlWM2J3ZjhKbWNlbEZveHlid1hFenEveHJaMjdvR05ZYTU2U0pL
    UndCQVJBVmhvNXdPRGZ3aFMKdWlQTEdMVm1RTEdxOHNmR2dNcGpuODd5MGhXSW9EN0ZPYnUzOFNo
    WTBrUVpqRk5vY2JWRmFMZUl1NHY5R1BLVQpPUzNjWWExYmVXanFsNTNLeWdmY3VJU0hwRG5DNU8r
    UHZyUjF2QVdEM25aamlYNVJrb1dpNXFWS2E0eE4xc2RrCjhaMGk1MXRSK1dEWCtOSGhqVW5oSERu
    U293VkZNQnhUQlVQRHlDUHh1dFhaZmZiZGd4RUVNVkk4cjBHYVlzQkYKTVhxV3FyUHVzMnJpNGpF
    YUI5bEtMdVRNLzNxWmdxdXB4aWQwdDdGdnRhbXpxYzhnOFVtZHV5c2txTjFLVmdSZApFQ2kzCi0t
    LS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcDJ0ejY4c21P
    dVk5WWNKSklBamhzS3loY0ltN1UyWEZ6QWZWMk1oS3FydHFZL1AwCkVWZGhUR1BWeVB5RCtsa2hD
    NlNVSjlMR3FpOHl6OTFzTGVqRDRPcmZSVkNhSGQzYlBBK2MyeDRZYVpsaVpYZGwKeklQUUd5MHdh
    aWJ5bmRmbVYrTmJjVVpyWEgzbVRkYitqcnV6L2lQZUs0RnJCbTBNd2hFK2ErNXhxN21UM3BHVApm
    VzUzZ3VTVWtMaTArODJPbzFhZVB4RG0zVVVPcnI2UU1zbDNhZ0lCUm1UMUE1UlBxYTRyMGNqdCtV
    SzF3YWFtCmJnNFVPUHhmcE9mMXNyM09rMGNZUzUzNGhlRm5FTGxqNmkyRUgyRTlWT0p3YlNtQXpM
    QWtWS0RDd1FoM0ZNdjIKcGVlT3NqR3BleHJTV3RqbXZ3emRjU2Vkdm9xVUJNQXpkQy9YTlFJREFR
    QUJBb0lCQUF4RnNDV2txcFMrczlrcQpxTG1VYlJiS1VMc3pIV3dybGFnekd0WGRPTHZ6S1FWU3FK
    MXN6bEVQTUdpZk9mMXI4eVFyV0VEakRuVURLTEpjCkJNWUl2Zk1LeEhzTVFYL1c5MjhicGQvYUFP
    Z2N1ajI5MXRSN0JSSTQ2Y2VlTzBLZXhOL0VacnVTOGVQQnh0UUYKNG5zTC8xR3R4MmRoQVR0ald3
    QU95NGlWM2ZjOGNOeW9iYVNZQ1NNOXh3cS8vU25hNWFlMUlEaHNteXM3a043NgpxbjltWnlpSWRk
    bi8yM0tsUjc4KzFzZlNKdCtTY05GRDdIMTdHNEs0NE1vQ3J5MVdsZFVRNUpPSFVNRUpldkY0CkY3
    Vm1URmhvL0ZrODhpNGZjS1lZTkFwNkpDT1FtaEo4ME5MWU93eFBQQkJxbm12ODJBdmM1R1hHV1Ny
    RVV3MDMKVDZEL3M3RUNnWUVBMklweVhiLzZVbG5TcENxOHRIYU1SS0IxbTRENVRLa3dnMUtsWmJH
    RDRqYWdEWDkwYURkMgpBVy9yVEpZc0Y4TEpDWmloNkZkN2xjVmhhcVQwLzhJUTl5YlhYNG9rZFRY
    aCt0N2Nna29ydWFCMDBSU1dHVk5qCmduSnhsRXFLMlM5WWYyeDJBMG1aM09UTm9LeDhXWXpRalgx
    Mm9DSm54QmJZdyt1T1JWUkhvSHNDZ1lFQXhlMkcKZDhPTHRwSTJzWDFGSG5vcTd4RndRVlBsaUU2
    VU9CZnB4RXNWRDJWSUNJa0lqempKKzBleEVuWXVSMDU5NmpSRwp1aTB3TFNSS2FRUUc3eDR5VWpo
    SC9McmZZdVRmNEd1dDdLRXQwano4eTZCY3lNTWxWdkdLSG45ckNRWjFESmhvCmlDbE5sL3RQalRJ
    RkQ4c1dha1ZmcUdJQUVRUWY2dCs2OGJ0VlVBOENnWUVBejkvSWZwdEhjVHJ0YmMvaEs5VUsKUHU5
    VE41OE90RHRQYVNJenlYWXFSMFZ0VE1mb05ndlg2dlZJQzFPMnJIQy9rY2pHMVViMlN3Y2F4OGZu
    c29iWQp4b3F4QXZTWW56VEU1WktBV1V0ZXdtcDQraVlyR2REbG5GckZFamlsSm0yL0pVUTMzbHdQ
    cXZDelBlV1gwbGZOCjlhWlY5TkJTa1BubHlkOGR5d3huWG5VQ2dZQjhJb2VXYjRjZG4wQThPelB4
    ZEcrZTl0SHZ0djJiYXFVZE5TcEIKR1ZJQkVPV0hyT0k0YVVhTW1aOGQxQThjVzhjdTcxQjRqY1RN
    V3hsc0djRjdrUFhBaVZuazBSTXZoQnBCTjJlaQpwRWdIdG9aWjg1NmRyMzZvczk2TFdDQzZUVmwx
    NTlTUHFVL29CUThVb0ExNnBVWE9xdW5ld25BR1BBOEVrUU0vCmZ0MTMwd0tCZ1FDaWhSZHZIM01l
    NythR0NiTEpSOTd6MHlBR2VZcFZIaGJZbVB2SkF4cXp1TXVGYXdoM1kvL0kKVE8zOUo4YzhHMHM3
    UWpBN3BEd1hTQVZ1UFNQOUorRTZiRVUwT3Uyc2lPZkJmMXZycmZma3JJNkZGMVkzaEFBMgo3ZlFW
    N0Z1b2I0Z2Raa0R6cTZ0M3VYV2RZVGlKY2hXN0NWL1hIR2FGbHplWEpDbzVOaS8wOHc9PQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls
